id: PD5823F56
initial_creation_type: ocr
source_metadata:
  volumes:
    8d35a2ea4f314494b30ce9cfa87f2982:
      base_file: v042.txt
      image_group_id: I1PD95887
      title: ''
      total_pages: 1712
      volume_number: 42
