id: D6A08B166
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-19T06:50:37+00:00'
last_modified: '2022-05-30T06:50:30.265221+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    d751:
      image_group_id: I1PD95887
      title: ''
      total_pages: 1712
      order: 42
      base_file: d751.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
